# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mlw4QJ9AzrzqkV3bXa-tuyXv3s2V7sym
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("M200 calculation - constant M_L.csv")

df.head()

print(df.columns)

# Gravitational constant
G = 4.30091e-6      # kpc (km/s)^2 Msun^-1

# Hubble constant
H0 = 70/1000        # km/s/kpc
df["M200"] = df["V200_const"]**3 / (10 * G * H0)

df["logM200"] = np.log10(df["M200"])

df

df = pd.read_csv("M200 calculation - min disk.csv")

df.head()

print(df.columns)

# Gravitational constant
G = 4.30091e-6      # kpc (km/s)^2 Msun^-1

# Hubble constant
H0 = 70/1000        # km/s/kpc
df["M200"] = df["V200_min disk"]**3 / (10 * G * H0)

df["logM200"] = np.log10(df["M200"])

plt.hist(df["logM200"], bins=10, edgecolor='black')
plt.xlabel("logM200")
plt.ylabel("Frequency")
plt.title("Histogram of logM200")
plt.show()

df

